Traceback (most recent call last):
  File "/Users/parjinder/code/python2os/./streams_err.py", line 5, in <module>
    raise ValueError("Now we generate an error to STDERR")
ValueError: Now we generate an error to STDERR
